# Generated by Django 2.0.4 on 2018-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='firstName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
