# Generated by Django 2.0.4 on 2018-05-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_game_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Welcome',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
